import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

import Row from '../components/Row'
import Column from '../components/Column'
import Text from '../components/Text'
import Button from '../components/Button'
import Stack from '../components/Stack'

export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Light House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/img_image8.png" />
      </Head>

      <div className={styles.main}>
        <div className={styles['landing-page']}>
          <div className={styles['image8']}>
            <Image
              src={'/images/img_image8.png'}
              width={128}
              height={128}
              alt={"imageEight"}
            />
          </div>

          <span className={styles['text']}>
            <span>Bible Quiz</span>
          </span>

          <Button
            className=" absolute top-[100px] left-[1200px] h-[auto] self-center mr-0 mb-0 font-normal border border-solid border-[#015EBF] rounded-3xl not-italic lg:text-[17px] xl:text-[19px] 2xl:text-[22px] 3xl:text-[26px] text-blue_800 text-center w-[200px]"
            shape="RoundedBorder15"
            variant="OutlineBlue8001_2"
            onClick={() => router.push('/signup')}>
            Sign up
          </Button> 

          <div className={styles['hidden']}>
          <div className={styles['ellipse1']}>
            <Image
              src="/images/ellipse12172.png"
              width={286}
              height={282}
              alt="Ellipse12172"
            />
          </div>

          <div className={styles['ellipse2']}>
            <Image
              src="/images/ellipse22172.png"
              width={286}
              height={282}
              alt="Ellipse22172"
            />
          </div>

          <div className={styles['ellipse3']}>
            <Image
              src="/images/ellipse32172.png"
              width={286}
              height={280}
              alt="Ellipse32172"
            />
          </div>

          <div className={styles['ellipse4']}>
            <Image
              src="/images/ellipse42172.png"
              width={286}
              height={282}
              alt="Ellipse42172"
            />
          </div>

          <div className={styles['ellipse6']}>
            <Image
              src="/images/ellipse62172.png"
              width={286}
              height={281}
              alt="Ellipse62172"
            />
          </div>

          <div className={styles['ellipse5']}>
            <Image
              src="/images/ellipse52172.png"
              width={286}
              height={281}
              alt="Ellipse52172"
            />
          </div>

          </div>

          <span className={styles['text06']}>
            <span>© Lighthouse. All rights reserved.</span>
          </span>

          <div className={styles['ellipse9']}>
            <Image
              src="/images/ellipse92172.png"
              width={20}
              height={20}
              alt="Ellipse92172"
            />
          </div>

          <div className={styles['ellipse10']}>
            <Image
              src="/images/ellipse102172.png"
              width={20}
              height={20}
              alt="Ellipse102172"
            />
          </div>

          <div className={styles['ellipse7']}>
            <Image
              src="/images/ellipse72172.png"
              width={20}
              height={20}
              alt="Ellipse72172"
            />
          </div>

          <div className={styles['ellipse8']}>
            <Image
              src="/images/ellipse82172.png"
              width={20}
              height={20}
              alt="Ellipse82172"
            />
          </div>


          <div className={styles['illustration']}>
            <Image
             src={"/images/img_illustration.svg"}
              width={683}
              height={490}
              alt="Illustration2172"
            />
          </div>

          <Button
          className={styles['btn_get_started']}
            shape="RoundedBorder24"
            size="xl"
            variant="OutlineBlue800"
            onClick={() => router.push('/signin')}>
            Get Started
          </Button>

          <span className={styles['text10']}>
            <span>Light house</span>
          </span>
          <span className={styles['text12']}>
            <span>We offer a wide variety of Biblical quizzes.</span>
          </span>
        </div>
      </div>

    </div>
  )
}
