import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Summary.module.css'
import { useRouter } from 'next/router'
import { useSession, getSession, signOut } from 'next-auth/react'

import Button from '../components/Button'
import Row from '../components/Row'
import Column from '../components/Column'
import Text from '../components/Text'
import Stack from '../components/Stack'

export default function QuizSummary() {
  const router = useRouter()
  const { data: session, status } = useSession({ required: true })
  if (session && status === 'authenticated') {
    return (
      <div className={styles.container}>
        <Head>
          <title>Light House</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="images/img_image8.png" />
        </Head>

        <div className={styles.main}>
          <div className={styles['quizsummary']}>

            <Stack className={styles['rectangle1913']}>
              <Image
                width={587}
                height={130}
                src={'/images/img_rectangle1910.png'}
                // src="/playground_assets/rectangle19105866-xjt9-600w.png"
                alt="Rectangle19105866"
              />
            </Stack>

            <Stack className={styles['rectangle1912']}>
              <Image
                width={587}
                height={130}
                src={'/images/img_rectangle1910.png'}
                // src="/playground_assets/rectangle19105866-xjt9-600w.png"
                alt="Rectangle19105866"
              />
            </Stack>

            <div className={styles['group135']}>
              <div className={styles['frame64']}>
                <div className={styles['frame23']}>
                  <span className={styles['text']}>
                    <span>Summary</span>
                  </span>
                  <div className={styles['frame75']}>
                    <div className={styles['frame18']}>
                      <span className={styles['text02']}>
                        <span>Total time</span>
                      </span>
                      <span className={styles['text04']}>
                        <span>50 secs</span>
                      </span>
                    </div>
                    <div className={styles['frame19']}>
                      <span className={styles['text06']}>
                        <span>Total Points</span>
                      </span>
                      <span className={styles['text08']}>
                        <span>20</span>
                      </span>
                    </div>
                    <div className={styles['frame20']}>
                      <span className={styles['text10']}>
                        <span>No of Questions</span>
                      </span>
                      <span className={styles['text12']}>
                        <span>10</span>
                      </span>
                    </div>
                  </div>

                  <div>
                    <Button
                      className={styles['btn_get_started']}
                      shape="RoundedBorder24"
                      size="xl"
                      variant="OutlineBlue800"
                      onClick={() => router.push('/quiz')}>
                      Get Started
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    )
  } else {
    return (
      <div className="flex flex-col items-center justify-center font-opensans items-center mx-[auto] lg:p-[18px] xl:p-[21px] 2xl:p-[24px] 3xl:p-[28px] w-[50%] max-h-screen">
        <Text className="font-semibold lg:text-[31px] xl:text-[35px] 2xl:text-[40px] 3xl:text-[48px] text-black_900 w-[auto]">
          You are not signed in
        </Text>

        <Button
          className="border-none rounded-none font-semibold bg-[#005EBF] text-[#ffffff] lg:mt-[24px] xl:mt-[28px] 2xl:mt-[32px] 3xl:mt-[38px] lg:text-[12px] xl:text-[14px] 2xl:text-2xl 3xl:text-[19px] text-center w-[100%]"
          shape="RoundedBorder24"
          size="lg"
          variant="OutlineBlue800"
          onClick={() => router.push('/signin')}>
          Sign In
        </Button>

      </div>
    )
  }
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/signin",
        permanent: false
      }
    };
  }
  return {
    props: { session },
  };
}

