import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useSession, getSession, signOut, signIn } from 'next-auth/react'

import Row from '../components/Row'
import Column from '../components/Column'
import Text from '../components/Text'
import Button from '../components/Button'
import Stack from '../components/Stack'

export default function Home() {
    const router = useRouter()
  const { data: session, status } = useSession({required: true})
  if (status === 'authenticated') {
  return (
    <div className={styles.container}>
      <Head>
        <title>Light House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/img_image8.png" />
      </Head>

      <div className={styles.main}>
        <div className={styles['landing-page']}>
          <div className={styles['image8']}>
            <Image
              src={'/images/img_image8.png'}
              width={128}
              height={128}
              alt={"imageEight"}
            />
          </div>
          <div 
           className="absolute top-[71px] left-[600px] h-[auto] self-center mr-[0] mb-0 font-normal 2xl:ml-[10px] 3xl:ml-[12px] lg:ml-[7px] xl:ml-[8px] not-italic lg:text-[17px] xl:text-[19px] 2xl:text-[32px] 3xl:text-[26px] text-center text-white_A700 w-[auto]">
            Welcome, {session.user.name}
           </div>

          <span className={styles['text']}>
            <span>Bible Quiz</span>
          </span>

            <Button
            className="absolute top-[71px] left-[1100px] h-[auto] self-center mr-[0] mb-0 font-normal bg-[#DD086C] text-[#ffffff] 2xl:ml-[10px] 3xl:ml-[12px] lg:ml-[7px] xl:ml-[8px] not-italic lg:text-[17px] xl:text-[19px] 2xl:text-[22px] 3xl:text-[26px] text-center text-white_A700 w-[200px] rounded-3xl"
            shape="RoundedBorder15"
            variant="OutlineBlue8001_2"
            onClick={() => signOut()}>
            Sign out
          </Button>
          

          <div className={styles['ellipse1']}>
            <Image
              src="/images/ellipse12172.png"
              width={286}
              height={282}
              alt="Ellipse12172"
            />
          </div>

          <div className={styles['ellipse2']}>
            <Image
              src="/images/ellipse22172.png"
              width={286}
              height={282}
              alt="Ellipse22172"
            />
          </div>

          <div className={styles['ellipse3']}>
            <Image
              src="/images/ellipse32172.png"
              width={286}
              height={280}
              alt="Ellipse32172"
            />
          </div>

          <div className={styles['ellipse4']}>
            <Image
              src="/images/ellipse42172.png"
              width={286}
              height={282}
              alt="Ellipse42172"
            />
          </div>

          <div className={styles['ellipse6']}>
            <Image
              src="/images/ellipse62172.png"
              width={286}
              height={281}
              alt="Ellipse62172"
            />
          </div>

          <div className={styles['ellipse5']}>
            <Image
              src="/images/ellipse52172.png"
              width={286}
              height={281}
              alt="Ellipse52172"
            />
          </div>

          <span className={styles['text06']}>
            <span>© Lighthouse. All rights reserved.</span>
          </span>

          <div className={styles['ellipse9']}>
            <Image
              src="/images/ellipse92172.png"
              width={20}
              height={20}
              alt="Ellipse92172"
            />
          </div>

          <div className={styles['ellipse10']}>
            <Image
              src="/images/ellipse102172.png"
              width={20}
              height={20}
              alt="Ellipse102172"
            />
          </div>

          <div className={styles['ellipse7']}>
            <Image
              src="/images/ellipse72172.png"
              width={20}
              height={20}
              alt="Ellipse72172"
            />
          </div>

          <div className={styles['ellipse8']}>
            <Image
              src="/images/ellipse82172.png"
              width={20}
              height={20}
              alt="Ellipse82172"
            />
          </div>


          <div className={styles['illustration']}>
            <Image
             src={"/images/img_illustration.svg"}
              width={683}
              height={490}
              alt="Illustration2172"
            />
          </div>

          <Button
            className={styles['btn_get_started']}
            shape="RoundedBorder24"
            size="xl"
            variant="OutlineBlue800"
            onClick={() => router.push('/join')}>
            Get Started
          </Button>

          <span className={styles['text10']}>
            <span>Light house</span>
          </span>
          <span className={styles['text12']}>
            <span>We offer a wide variety of Biblical quizzes.</span>
          </span>
        </div>
      </div>

    </div>
    )
} else {
  return (
    <div className="flex flex-col items-center justify-center font-opensans items-center mx-[auto] lg:p-[18px] xl:p-[21px] 2xl:p-[24px] 3xl:p-[28px] w-[100%] max-h-screen">
      <Text className="font-semibold lg:text-[31px] xl:text-[35px] 2xl:text-[40px] 3xl:text-[48px] text-black_900 w-[auto]">
        You are not signed in
      </Text>

      <Button
        className="border-none rounded-none font-semibold bg-[#005EBF] text-[#ffffff] lg:mt-[24px] xl:mt-[28px] 2xl:mt-[32px] 3xl:mt-[38px] lg:text-[12px] xl:text-[14px] 2xl:text-2xl 3xl:text-[19px] text-center w-[50%]"
        shape="RoundedBorder24"
        size="lg"
        variant="OutlineBlue800"
        onClick={() => router.push('/signin')}>
        Sign In
      </Button>

    </div>
  )
}
}
